#![doc = "Peripheral access API for MK20D5 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn DMA0();
    fn DMA1();
    fn DMA2();
    fn DMA3();
    fn DMA_Error();
    fn FTFL();
    fn Read_Collision();
    fn LVD_LVW();
    fn LLW();
    fn Watchdog();
    fn I2C0();
    fn SPI0();
    fn I2S0_Tx();
    fn I2S0_Rx();
    fn UART0_LON();
    fn UART0_RX_TX();
    fn UART0_ERR();
    fn UART1_RX_TX();
    fn UART1_ERR();
    fn UART2_RX_TX();
    fn UART2_ERR();
    fn ADC0();
    fn CMP0();
    fn CMP1();
    fn FTM0();
    fn FTM1();
    fn CMT();
    fn RTC();
    fn RTC_Seconds();
    fn PIT0();
    fn PIT1();
    fn PIT2();
    fn PIT3();
    fn PDB0();
    fn USB0();
    fn USBDCD();
    fn TSI0();
    fn LPTimer();
    fn PORTA();
    fn PORTB();
    fn PORTC();
    fn PORTD();
    fn PORTE();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 45] = [
    Vector { _handler: DMA0 },
    Vector { _handler: DMA1 },
    Vector { _handler: DMA2 },
    Vector { _handler: DMA3 },
    Vector {
        _handler: DMA_Error,
    },
    Vector { _reserved: 0 },
    Vector { _handler: FTFL },
    Vector {
        _handler: Read_Collision,
    },
    Vector { _handler: LVD_LVW },
    Vector { _handler: LLW },
    Vector { _handler: Watchdog },
    Vector { _handler: I2C0 },
    Vector { _handler: SPI0 },
    Vector { _handler: I2S0_Tx },
    Vector { _handler: I2S0_Rx },
    Vector {
        _handler: UART0_LON,
    },
    Vector {
        _handler: UART0_RX_TX,
    },
    Vector {
        _handler: UART0_ERR,
    },
    Vector {
        _handler: UART1_RX_TX,
    },
    Vector {
        _handler: UART1_ERR,
    },
    Vector {
        _handler: UART2_RX_TX,
    },
    Vector {
        _handler: UART2_ERR,
    },
    Vector { _handler: ADC0 },
    Vector { _handler: CMP0 },
    Vector { _handler: CMP1 },
    Vector { _handler: FTM0 },
    Vector { _handler: FTM1 },
    Vector { _handler: CMT },
    Vector { _handler: RTC },
    Vector {
        _handler: RTC_Seconds,
    },
    Vector { _handler: PIT0 },
    Vector { _handler: PIT1 },
    Vector { _handler: PIT2 },
    Vector { _handler: PIT3 },
    Vector { _handler: PDB0 },
    Vector { _handler: USB0 },
    Vector { _handler: USBDCD },
    Vector { _handler: TSI0 },
    Vector { _reserved: 0 },
    Vector { _handler: LPTimer },
    Vector { _handler: PORTA },
    Vector { _handler: PORTB },
    Vector { _handler: PORTC },
    Vector { _handler: PORTD },
    Vector { _handler: PORTE },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - DMA0"]
    DMA0 = 0,
    #[doc = "1 - DMA1"]
    DMA1 = 1,
    #[doc = "2 - DMA2"]
    DMA2 = 2,
    #[doc = "3 - DMA3"]
    DMA3 = 3,
    #[doc = "4 - DMA_Error"]
    DMA_Error = 4,
    #[doc = "6 - FTFL"]
    FTFL = 6,
    #[doc = "7 - Read_Collision"]
    Read_Collision = 7,
    #[doc = "8 - LVD_LVW"]
    LVD_LVW = 8,
    #[doc = "9 - LLW"]
    LLW = 9,
    #[doc = "10 - Watchdog"]
    Watchdog = 10,
    #[doc = "11 - I2C0"]
    I2C0 = 11,
    #[doc = "12 - SPI0"]
    SPI0 = 12,
    #[doc = "13 - I2S0_Tx"]
    I2S0_Tx = 13,
    #[doc = "14 - I2S0_Rx"]
    I2S0_Rx = 14,
    #[doc = "15 - UART0_LON"]
    UART0_LON = 15,
    #[doc = "16 - UART0_RX_TX"]
    UART0_RX_TX = 16,
    #[doc = "17 - UART0_ERR"]
    UART0_ERR = 17,
    #[doc = "18 - UART1_RX_TX"]
    UART1_RX_TX = 18,
    #[doc = "19 - UART1_ERR"]
    UART1_ERR = 19,
    #[doc = "20 - UART2_RX_TX"]
    UART2_RX_TX = 20,
    #[doc = "21 - UART2_ERR"]
    UART2_ERR = 21,
    #[doc = "22 - ADC0"]
    ADC0 = 22,
    #[doc = "23 - CMP0"]
    CMP0 = 23,
    #[doc = "24 - CMP1"]
    CMP1 = 24,
    #[doc = "25 - FTM0"]
    FTM0 = 25,
    #[doc = "26 - FTM1"]
    FTM1 = 26,
    #[doc = "27 - CMT"]
    CMT = 27,
    #[doc = "28 - RTC"]
    RTC = 28,
    #[doc = "29 - RTC_Seconds"]
    RTC_Seconds = 29,
    #[doc = "30 - PIT0"]
    PIT0 = 30,
    #[doc = "31 - PIT1"]
    PIT1 = 31,
    #[doc = "32 - PIT2"]
    PIT2 = 32,
    #[doc = "33 - PIT3"]
    PIT3 = 33,
    #[doc = "34 - PDB0"]
    PDB0 = 34,
    #[doc = "35 - USB0"]
    USB0 = 35,
    #[doc = "36 - USBDCD"]
    USBDCD = 36,
    #[doc = "37 - TSI0"]
    TSI0 = 37,
    #[doc = "39 - LPTimer"]
    LPTimer = 39,
    #[doc = "40 - PORTA"]
    PORTA = 40,
    #[doc = "41 - PORTB"]
    PORTB = 41,
    #[doc = "42 - PORTC"]
    PORTC = 42,
    #[doc = "43 - PORTD"]
    PORTD = 43,
    #[doc = "44 - PORTE"]
    PORTE = 44,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Flash configuration field"]
pub type FtflFlashConfig = crate::Periph<ftfl_flash_config::RegisterBlock, 0x0400>;
impl core::fmt::Debug for FtflFlashConfig {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FtflFlashConfig").finish()
    }
}
#[doc = "Flash configuration field"]
pub mod ftfl_flash_config;
#[doc = "Enhanced direct memory access controller"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "Enhanced direct memory access controller"]
pub mod dma;
#[doc = "Flash Memory Controller"]
pub type Fmc = crate::Periph<fmc::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Fmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fmc").finish()
    }
}
#[doc = "Flash Memory Controller"]
pub mod fmc;
#[doc = "Flash Memory Interface"]
pub type Ftfl = crate::Periph<ftfl::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Ftfl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ftfl").finish()
    }
}
#[doc = "Flash Memory Interface"]
pub mod ftfl;
#[doc = "DMA channel multiplexor"]
pub type Dmamux = crate::Periph<dmamux::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Dmamux {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmamux").finish()
    }
}
#[doc = "DMA channel multiplexor"]
pub mod dmamux;
#[doc = "Deserial Serial Peripheral Interface"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4002_c000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "Deserial Serial Peripheral Interface"]
pub mod spi0;
#[doc = "Inter-IC Sound / Synchronous Audio Interface"]
pub type I2s0 = crate::Periph<i2s0::RegisterBlock, 0x4002_f000>;
impl core::fmt::Debug for I2s0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s0").finish()
    }
}
#[doc = "Inter-IC Sound / Synchronous Audio Interface"]
pub mod i2s0;
#[doc = "Cyclic Redundancy Check"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4003_2000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "Cyclic Redundancy Check"]
pub mod crc;
#[doc = "USB Device Charger Detection module"]
pub type Usbdcd = crate::Periph<usbdcd::RegisterBlock, 0x4003_5000>;
impl core::fmt::Debug for Usbdcd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbdcd").finish()
    }
}
#[doc = "USB Device Charger Detection module"]
pub mod usbdcd;
#[doc = "Programmable Delay Block"]
pub type Pdb0 = crate::Periph<pdb0::RegisterBlock, 0x4003_6000>;
impl core::fmt::Debug for Pdb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pdb0").finish()
    }
}
#[doc = "Programmable Delay Block"]
pub mod pdb0;
#[doc = "Periodic Interrupt Timer"]
pub type Pit = crate::Periph<pit::RegisterBlock, 0x4003_7000>;
impl core::fmt::Debug for Pit {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pit").finish()
    }
}
#[doc = "Periodic Interrupt Timer"]
pub mod pit;
#[doc = "FlexTimer Module"]
pub type Ftm0 = crate::Periph<ftm0::RegisterBlock, 0x4003_8000>;
impl core::fmt::Debug for Ftm0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ftm0").finish()
    }
}
#[doc = "FlexTimer Module"]
pub mod ftm0;
#[doc = "FlexTimer Module"]
pub type Ftm1 = crate::Periph<ftm1::RegisterBlock, 0x4003_9000>;
impl core::fmt::Debug for Ftm1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ftm1").finish()
    }
}
#[doc = "FlexTimer Module"]
pub mod ftm1;
#[doc = "Analog-to-Digital Converter"]
pub type Adc0 = crate::Periph<adc0::RegisterBlock, 0x4003_b000>;
impl core::fmt::Debug for Adc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0").finish()
    }
}
#[doc = "Analog-to-Digital Converter"]
pub mod adc0;
#[doc = "Secure Real Time Clock"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4003_d000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "Secure Real Time Clock"]
pub mod rtc;
#[doc = "VBAT register file"]
pub type Rfvbat = crate::Periph<rfvbat::RegisterBlock, 0x4003_e000>;
impl core::fmt::Debug for Rfvbat {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rfvbat").finish()
    }
}
#[doc = "VBAT register file"]
pub mod rfvbat;
#[doc = "Low Power Timer"]
pub type Lptmr0 = crate::Periph<lptmr0::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for Lptmr0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptmr0").finish()
    }
}
#[doc = "Low Power Timer"]
pub mod lptmr0;
#[doc = "System register file"]
pub type Rfsys = crate::Periph<rfsys::RegisterBlock, 0x4004_1000>;
impl core::fmt::Debug for Rfsys {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rfsys").finish()
    }
}
#[doc = "System register file"]
pub mod rfsys;
#[doc = "Touch Sensing Input"]
pub type Tsi0 = crate::Periph<tsi0::RegisterBlock, 0x4004_5000>;
impl core::fmt::Debug for Tsi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tsi0").finish()
    }
}
#[doc = "Touch Sensing Input"]
pub mod tsi0;
#[doc = "System Integration Module"]
pub type Sim = crate::Periph<sim::RegisterBlock, 0x4004_7000>;
impl core::fmt::Debug for Sim {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sim").finish()
    }
}
#[doc = "System Integration Module"]
pub mod sim;
#[doc = "Pin Control and Interrupts"]
pub type Porta = crate::Periph<porta::RegisterBlock, 0x4004_9000>;
impl core::fmt::Debug for Porta {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Porta").finish()
    }
}
#[doc = "Pin Control and Interrupts"]
pub mod porta;
#[doc = "Pin Control and Interrupts"]
pub type Portb = crate::Periph<portb::RegisterBlock, 0x4004_a000>;
impl core::fmt::Debug for Portb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Portb").finish()
    }
}
#[doc = "Pin Control and Interrupts"]
pub mod portb;
#[doc = "Pin Control and Interrupts"]
pub type Portc = crate::Periph<portc::RegisterBlock, 0x4004_b000>;
impl core::fmt::Debug for Portc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Portc").finish()
    }
}
#[doc = "Pin Control and Interrupts"]
pub mod portc;
#[doc = "Pin Control and Interrupts"]
pub type Portd = crate::Periph<portd::RegisterBlock, 0x4004_c000>;
impl core::fmt::Debug for Portd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Portd").finish()
    }
}
#[doc = "Pin Control and Interrupts"]
pub mod portd;
#[doc = "Pin Control and Interrupts"]
pub type Porte = crate::Periph<porte::RegisterBlock, 0x4004_d000>;
impl core::fmt::Debug for Porte {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Porte").finish()
    }
}
#[doc = "Pin Control and Interrupts"]
pub mod porte;
#[doc = "Generation 2008 Watchdog Timer"]
pub type Wdog = crate::Periph<wdog::RegisterBlock, 0x4005_2000>;
impl core::fmt::Debug for Wdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog").finish()
    }
}
#[doc = "Generation 2008 Watchdog Timer"]
pub mod wdog;
#[doc = "External Watchdog Monitor"]
pub type Ewm = crate::Periph<ewm::RegisterBlock, 0x4006_1000>;
impl core::fmt::Debug for Ewm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ewm").finish()
    }
}
#[doc = "External Watchdog Monitor"]
pub mod ewm;
#[doc = "Carrier Modulator Transmitter"]
pub type Cmt = crate::Periph<cmt::RegisterBlock, 0x4006_2000>;
impl core::fmt::Debug for Cmt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmt").finish()
    }
}
#[doc = "Carrier Modulator Transmitter"]
pub mod cmt;
#[doc = "Multipurpose Clock Generator module"]
pub type Mcg = crate::Periph<mcg::RegisterBlock, 0x4006_4000>;
impl core::fmt::Debug for Mcg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mcg").finish()
    }
}
#[doc = "Multipurpose Clock Generator module"]
pub mod mcg;
#[doc = "Oscillator"]
pub type Osc0 = crate::Periph<osc0::RegisterBlock, 0x4006_5000>;
impl core::fmt::Debug for Osc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Osc0").finish()
    }
}
#[doc = "Oscillator"]
pub mod osc0;
#[doc = "Inter-Integrated Circuit"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4006_6000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "Inter-Integrated Circuit"]
pub mod i2c0;
#[doc = "Serial Communication Interface"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4006_a000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "Serial Communication Interface"]
pub mod uart0;
#[doc = "Serial Communication Interface"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4006_b000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "Serial Communication Interface"]
pub mod uart1;
#[doc = "Serial Communication Interface"]
pub type Uart2 = crate::Periph<uart2::RegisterBlock, 0x4006_c000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "Serial Communication Interface"]
pub mod uart2;
#[doc = "Universal Serial Bus, OTG Capable Controller"]
pub type Usb0 = crate::Periph<usb0::RegisterBlock, 0x4007_2000>;
impl core::fmt::Debug for Usb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usb0").finish()
    }
}
#[doc = "Universal Serial Bus, OTG Capable Controller"]
pub mod usb0;
#[doc = "High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)"]
pub type Cmp0 = crate::Periph<cmp0::RegisterBlock, 0x4007_3000>;
impl core::fmt::Debug for Cmp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp0").finish()
    }
}
#[doc = "High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)"]
pub mod cmp0;
#[doc = "High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)"]
pub type Cmp1 = crate::Periph<cmp1::RegisterBlock, 0x4007_3008>;
impl core::fmt::Debug for Cmp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp1").finish()
    }
}
#[doc = "High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)"]
pub mod cmp1;
#[doc = "Voltage Reference"]
pub type Vref = crate::Periph<vref::RegisterBlock, 0x4007_4000>;
impl core::fmt::Debug for Vref {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vref").finish()
    }
}
#[doc = "Voltage Reference"]
pub mod vref;
#[doc = "Low leakage wakeup unit"]
pub type Llwu = crate::Periph<llwu::RegisterBlock, 0x4007_c000>;
impl core::fmt::Debug for Llwu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Llwu").finish()
    }
}
#[doc = "Low leakage wakeup unit"]
pub mod llwu;
#[doc = "Power Management Controller"]
pub type Pmc = crate::Periph<pmc::RegisterBlock, 0x4007_d000>;
impl core::fmt::Debug for Pmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pmc").finish()
    }
}
#[doc = "Power Management Controller"]
pub mod pmc;
#[doc = "System Mode Controller"]
pub type Smc = crate::Periph<smc::RegisterBlock, 0x4007_e000>;
impl core::fmt::Debug for Smc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Smc").finish()
    }
}
#[doc = "System Mode Controller"]
pub mod smc;
#[doc = "Reset Control Module"]
pub type Rcm = crate::Periph<rcm::RegisterBlock, 0x4007_f000>;
impl core::fmt::Debug for Rcm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rcm").finish()
    }
}
#[doc = "Reset Control Module"]
pub mod rcm;
#[doc = "General Purpose Input/Output"]
pub type Pta = crate::Periph<pta::RegisterBlock, 0x400f_f000>;
impl core::fmt::Debug for Pta {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pta").finish()
    }
}
#[doc = "General Purpose Input/Output"]
pub mod pta;
#[doc = "General Purpose Input/Output"]
pub type Ptb = crate::Periph<ptb::RegisterBlock, 0x400f_f040>;
impl core::fmt::Debug for Ptb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ptb").finish()
    }
}
#[doc = "General Purpose Input/Output"]
pub mod ptb;
#[doc = "General Purpose Input/Output"]
pub type Ptc = crate::Periph<ptc::RegisterBlock, 0x400f_f080>;
impl core::fmt::Debug for Ptc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ptc").finish()
    }
}
#[doc = "General Purpose Input/Output"]
pub mod ptc;
#[doc = "General Purpose Input/Output"]
pub type Ptd = crate::Periph<ptd::RegisterBlock, 0x400f_f0c0>;
impl core::fmt::Debug for Ptd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ptd").finish()
    }
}
#[doc = "General Purpose Input/Output"]
pub mod ptd;
#[doc = "General Purpose Input/Output"]
pub type Pte = crate::Periph<pte::RegisterBlock, 0x400f_f100>;
impl core::fmt::Debug for Pte {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pte").finish()
    }
}
#[doc = "General Purpose Input/Output"]
pub mod pte;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "FTFL_FlashConfig"]
    pub ftfl_flash_config: FtflFlashConfig,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "FMC"]
    pub fmc: Fmc,
    #[doc = "FTFL"]
    pub ftfl: Ftfl,
    #[doc = "DMAMUX"]
    pub dmamux: Dmamux,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "I2S0"]
    pub i2s0: I2s0,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "USBDCD"]
    pub usbdcd: Usbdcd,
    #[doc = "PDB0"]
    pub pdb0: Pdb0,
    #[doc = "PIT"]
    pub pit: Pit,
    #[doc = "FTM0"]
    pub ftm0: Ftm0,
    #[doc = "FTM1"]
    pub ftm1: Ftm1,
    #[doc = "ADC0"]
    pub adc0: Adc0,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "RFVBAT"]
    pub rfvbat: Rfvbat,
    #[doc = "LPTMR0"]
    pub lptmr0: Lptmr0,
    #[doc = "RFSYS"]
    pub rfsys: Rfsys,
    #[doc = "TSI0"]
    pub tsi0: Tsi0,
    #[doc = "SIM"]
    pub sim: Sim,
    #[doc = "PORTA"]
    pub porta: Porta,
    #[doc = "PORTB"]
    pub portb: Portb,
    #[doc = "PORTC"]
    pub portc: Portc,
    #[doc = "PORTD"]
    pub portd: Portd,
    #[doc = "PORTE"]
    pub porte: Porte,
    #[doc = "WDOG"]
    pub wdog: Wdog,
    #[doc = "EWM"]
    pub ewm: Ewm,
    #[doc = "CMT"]
    pub cmt: Cmt,
    #[doc = "MCG"]
    pub mcg: Mcg,
    #[doc = "OSC0"]
    pub osc0: Osc0,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "USB0"]
    pub usb0: Usb0,
    #[doc = "CMP0"]
    pub cmp0: Cmp0,
    #[doc = "CMP1"]
    pub cmp1: Cmp1,
    #[doc = "VREF"]
    pub vref: Vref,
    #[doc = "LLWU"]
    pub llwu: Llwu,
    #[doc = "PMC"]
    pub pmc: Pmc,
    #[doc = "SMC"]
    pub smc: Smc,
    #[doc = "RCM"]
    pub rcm: Rcm,
    #[doc = "PTA"]
    pub pta: Pta,
    #[doc = "PTB"]
    pub ptb: Ptb,
    #[doc = "PTC"]
    pub ptc: Ptc,
    #[doc = "PTD"]
    pub ptd: Ptd,
    #[doc = "PTE"]
    pub pte: Pte,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ftfl_flash_config: FtflFlashConfig::steal(),
            dma: Dma::steal(),
            fmc: Fmc::steal(),
            ftfl: Ftfl::steal(),
            dmamux: Dmamux::steal(),
            spi0: Spi0::steal(),
            i2s0: I2s0::steal(),
            crc: Crc::steal(),
            usbdcd: Usbdcd::steal(),
            pdb0: Pdb0::steal(),
            pit: Pit::steal(),
            ftm0: Ftm0::steal(),
            ftm1: Ftm1::steal(),
            adc0: Adc0::steal(),
            rtc: Rtc::steal(),
            rfvbat: Rfvbat::steal(),
            lptmr0: Lptmr0::steal(),
            rfsys: Rfsys::steal(),
            tsi0: Tsi0::steal(),
            sim: Sim::steal(),
            porta: Porta::steal(),
            portb: Portb::steal(),
            portc: Portc::steal(),
            portd: Portd::steal(),
            porte: Porte::steal(),
            wdog: Wdog::steal(),
            ewm: Ewm::steal(),
            cmt: Cmt::steal(),
            mcg: Mcg::steal(),
            osc0: Osc0::steal(),
            i2c0: I2c0::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            uart2: Uart2::steal(),
            usb0: Usb0::steal(),
            cmp0: Cmp0::steal(),
            cmp1: Cmp1::steal(),
            vref: Vref::steal(),
            llwu: Llwu::steal(),
            pmc: Pmc::steal(),
            smc: Smc::steal(),
            rcm: Rcm::steal(),
            pta: Pta::steal(),
            ptb: Ptb::steal(),
            ptc: Ptc::steal(),
            ptd: Ptd::steal(),
            pte: Pte::steal(),
        }
    }
}
